name: Mirror SCAN (simple)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 12 * * 1-5"   # 08:00 Toronto, weekdays

permissions:
  contents: write

jobs:
  mirror_scan:
    runs-on: ubuntu-latest
    env:
      SHEET_ID: 1iClfgrC4QaJ7Wb00dPoeg6DANCc1VisSqds-yhXtL2M
      SHEET_NAME: SCAN
      OUT_PATH: sheets/SCAN.csv
    steps:
      - uses: actions/checkout@v4

- name: Fetch SCAN via gviz (by name, no gid)
  run: |
    set -euo pipefail
    mkdir -p "$(dirname "$OUT_PATH")"
    # Force the pull to start at row 1
    URL="https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv&sheet=${SHEET_NAME}&range=A1:ZZZ100000"
    echo "Fetching: $URL"
    curl -fSLo "$OUT_PATH" "$URL"
    head -n 3 "$OUT_PATH" || true


      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Mirror SCAN (gviz): $(date -u +'%Y-%m-%dT%H:%MZ')"
          file_pattern: ${{ env.OUT_PATH }}
