name: Mirror SCAN (simple, header-safe)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 12 * * 1-5"   # 08:00 Toronto, weekdays

permissions:
  contents: write

jobs:
  mirror_scan:
    runs-on: ubuntu-latest
    env:
      SHEET_ID: 1iClfgrC4QaJ7Wb00dPoeg6DANCc1VisSqds-yhXtL2M
      SHEET_GID: "1375435285"          # <-- put the SCAN tab's gid here
      OUT_PATH: live/SCAN.csv          # (use live/ if you want it there)
      TZ: America/Toronto
    steps:
      - uses: actions/checkout@v4

      - name: Fetch SCAN via export (always has headers)
        run: |
          set -euo pipefail
          mkdir -p "$(dirname "$OUT_PATH")"
          URL="https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=${SHEET_GID}"
          echo "Fetching: $URL"
          curl -fSLA "mirror-scan/1.0" -o "$OUT_PATH" "$URL"
          test -s "$OUT_PATH"

          echo "First 5 lines:"
          head -n 5 "$OUT_PATH"

          # sanity: first cell should read Symbol
          first_cell="$(head -n1 "$OUT_PATH" | cut -d',' -f1)"
          if [ "$first_cell" != "Symbol" ]; then
            echo "ERROR: Header row not detected (first cell: '$first_cell')."
            echo "Tip: ensure SCAN tab row 1 contains headers and the gid is correct."
            exit 2
          fi

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Mirror SCAN (export): $(date -u +'%Y-%m-%dT%H:%MZ')"
          file_pattern: ${{ env.OUT_PATH }}

      - name: Upload artifact (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mirror-scan-output
          path: ${{ env.OUT_PATH }}
          if-no-files-found: warn
