name: Mirror SCAN from Google Sheets

on:
  workflow_dispatch:
  schedule:
    - cron: "30 13 * * 1-5"  # 09:30 Toronto ≈ 13:30 UTC

jobs:
  pull-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch SCAN CSV via gviz (by sheet name)
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1iClfgrC4QaJ7Wb00dPoeg6DANCc1VisSqds-yhXtL2M/gviz/tq?tqx=out:csv&sheet=SCAN" -o sheets/SCAN.csv

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add sheets/SCAN.csv
          git commit -m "Mirror: SCAN.csv from Google Sheets" || echo "No changes to commit"
          git push
