name: Mirror SCAN from Google Sheets (Export Endpoint)

on:
  workflow_dispatch:
  schedule:
    # 9:30 AM Toronto ≈ 13:30 UTC (Mon–Fri)
    - cron: "30 13 * * 1-5"

permissions:
  contents: write

jobs:
  pull-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Ensure target folder exists
        run: mkdir -p sheets

      - name: Fetch SCAN CSV (preserves headers)
        run: |
          curl -fSL \
            "https://docs.google.com/spreadsheets/d/1iClfgrC4QaJ7Wb00dPoeg6DANCc1VisSqds-yhXtL2M/export?format=csv&gid=1375435285" \
            -o sheets/SCAN.csv

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add sheets/SCAN.csv
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Mirror: SCAN.csv from Google Sheets (export)"
          git push
