name: Mirror SCAN (header-robust)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 12 * * 1-5"   # 08:00 Toronto, weekdays

permissions:
  contents: write

jobs:
  mirror_scan:
    runs-on: ubuntu-latest
    env:
      SHEET_ID: 1iClfgrC4QaJ7Wb00dPoeg6DANCc1VisSqds-yhXtL2M
      SHEET_GID: "1375435285"      # <-- confirm SCAN gid
      OUT_PATH: live/SCAN.csv
      TZ: America/Toronto
    steps:
      - uses: actions/checkout@v4

      - name: Fetch SCAN (header + body, export endpoint)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$(dirname "$OUT_PATH")"

          base="https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=${SHEET_GID}"

          # Fetch header-only (row 1) and body (row 2 onward)
          curl -fSLA "mirror-scan/1.1" -o /tmp/header.csv "${base}&range=A1:ZZZ1"
          curl -fSLA "mirror-scan/1.1" -o /tmp/body.csv   "${base}&range=A2:ZZZ100000"

          # Detect accidental HTML sign-in page
          if head -c 1 /tmp/header.csv | grep -q "<"; then
            echo "ERROR: Got HTML (sheet likely not shared 'Anyone with the link')."
            exit 3
          fi

          # Normalize line endings and strip UTF-8 BOM from header
          sed -i 's/\r$//' /tmp/header.csv
          sed -i 's/\r$//' /tmp/body.csv
          perl -CS -pe 's/^\x{FEFF}//;' -i /tmp/header.csv

          # Basic header sanity
          first_cell="$(head -n1 /tmp/header.csv | cut -d',' -f1)"
          if [ -z "$first_cell" ]; then
            echo "ERROR: Header row is empty. Check SCAN row 1 has column names."
            exit 2
          fi
          # Allow BOM/whitespace/case variance
          norm_first="$(echo "$first_cell" | tr -d '[:space:]' | tr '[:lower:]' '[:upper:]')"
          if [ "$norm_first" != "SYMBOL" ]; then
            echo "WARN: First header cell isn't 'Symbol' (it's '$first_cell'). Continuing anyway."
          fi

          # Assemble final CSV
          cat /tmp/header.csv > "$OUT_PATH"
          if [ -s /tmp/body.csv ]; then
            # Ensure we don't accidentally duplicate header if sheet had only 1 row
            cat /tmp/body.csv >> "$OUT_PATH"
          fi

          echo "First 5 lines:"
          head -n 5 "$OUT_PATH"

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Mirror SCAN (header-robust): $(date -u +'%Y-%m-%dT%H:%MZ')"
          file_pattern: ${{ env.OUT_PATH }}

      - name: Upload artifact (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mirror-scan-output
          path: ${{ env.OUT_PATH }}
          if-no-files-found: warn
