name: Mirror ALL sheets (morning)

on:
  schedule:
    - cron: "0 12 * * 1-5"   # 08:00 Toronto, weekdays
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  mirror_all:
    runs-on: ubuntu-latest
    env:
      SHEET_ID: 1iClfgrC4QaJ7Wb00dPoeg6DANCc1VisSqds-yhXtL2M
      OUT_DIR: sheets
      TZ: America/Toronto

    steps:
      - uses: actions/checkout@v4

      - name: Fetch workbook (XLSX)
        run: |
          set -euo pipefail
          mkdir -p tmp
          URL="https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=xlsx"
          echo "Fetching: $URL"
          curl -fSLo tmp/workbook.xlsx "$URL"
          ls -lh tmp/workbook.xlsx

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install xlsx2csv
        run: |
          python -m pip install --upgrade pip
          pip install xlsx2csv

      - name: Split each tab into its own CSV
        run: |
          set -euo pipefail
          mkdir -p "$OUT_DIR"
          # -a = all sheets, -d , = comma delimiter
          xlsx2csv -a -d , "tmp/workbook.xlsx" "$OUT_DIR"
          echo "Wrote CSVs:"
          ls -lh "$OUT_DIR"

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Mirror ALL sheets (morning)
          file_pattern: ${{ env.OUT_DIR }}/*.csv

      - name: Upload artifact (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mirror-all-output
          path: ${{ env.OUT_DIR }}/*.csv
          if-no-files-found: warn
