name: Morning Mirror — Full Workbook + Key CSVs

on:
  workflow_dispatch:
  schedule:
    # 08:00 Toronto ≈ 12:00 UTC (Mon–Fri). Change to "0 12 * * *" for every day.
    - cron: "0 12 * * 1-5"

permissions:
  contents: write

env:
  SHEET_ID: "1iClfgrC4QaJ7Wb00dPoeg6DANCc1VisSqds-yhXtL2M"
  PUB_E_ID: "2PACX-1vTpvBTBr4zzHKpcLc9V8vOCSFTvRJBaSvYWtOHrQbWTruTz3NYjAEfHnTDIdpCj2tCpYihiBXcjUHYh"
  GID_SCAN: "1375435285"

jobs:
  morning-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Ensure target folders
        run: |
          mkdir -p daily sheets

      - name: Timestamp (UTC & Toronto)
        id: ts
        run: |
          echo "UTC_DATE=$(date -u +%Y-%m-%d)" >> $GITHUB_OUTPUT
          echo "LOCAL_DATE=$(TZ=America/Toronto date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Write helper script (HTTP/1.1 + retry + published fallback)
        run: |
          cat > helper.sh <<'BASH'
          set -euo pipefail

          fetch_xlsx () {
            local out="$1"
            # Primary: /export?format=xlsx (SHEET_ID)
            if curl --http1.1 -fSL -A "GitHubActions/1.0" \
              "https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=xlsx" \
              -o "$out"; then
              echo "Saved XLSX via /export → $out"
              return 0
            fi
            echo "Primary XLSX failed, trying published fallback..."
            # Fallback: /d/e/.../pub?output=xlsx (PUB_E_ID)
            curl --http1.1 -fSL -A "GitHubActions/1.0" \
              "https://docs.google.com/spreadsheets/d/e/${PUB_E_ID}/pub?output=xlsx" \
              -o "$out"
            echo "Saved XLSX via /pub → $out"
          }

          fetch_csv () {
            local gid="$1"
            local out="$2"
            local tries=0
            local max=4
            local delay=3

            # Try primary /export?format=csv&gid=
            while (( tries < max )); do
              if curl --http1.1 -fSL -A "GitHubActions/1.0" \
                "https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=${gid}" \
                -o "$out"; then
                echo "Saved CSV via /export (gid=${gid}) → $out"
                return 0
              fi
              tries=$((tries+1))
              echo "Retry $tries/$max after ${delay}s…"
              sleep "${delay}"
            done

            echo "Primary CSV failed after retries, trying published fallback…"
            # Fallback: /d/e/.../pub?gid=...&single=true&output=csv
            curl --http1.1 -fSL -A "GitHubActions/1.0" \
              "https://docs.google.com/spreadsheets/d/e/${PUB_E_ID}/pub?gid=${gid}&single=true&output=csv" \
              -o "$out"
            echo "Saved CSV via /pub (gid=${gid}) → $out"
          }
          BASH
          chmod +x helper.sh

      - name: Download full workbook (XLSX, all tabs)
        run: |
          source ./helper.sh
          OUT="daily/Workbook_${{ steps.ts.outputs.LOCAL_DATE }}.xlsx"
          fetch_xlsx "${OUT}"

      - name: Download key tabs as CSV (add more as needed)
        run: |
          source ./helper.sh

          # Add more "NAME:gid" lines to mirror more tabs
          TABS=(
            "SCAN:${GID_SCAN}"
            # "SIGNALS:<gid_here>"
            # "PRICES:<gid_here>"
            # "HEALTH:<gid_here>"
          )

          for entry in "${TABS[@]}"; do
            NAME="${entry%%:*}"
            GID="${entry##*:}"
            echo "Fetching $NAME (gid=$GID)"
            fetch_csv "${GID}" "sheets/${NAME}.csv"
          done

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add daily/ sheets/
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Morning mirror: full workbook + key CSVs (${{ steps.ts.outputs.LOCAL_DATE }})"

      - name: Push
        run: git push
