name: Mirror SCAN from Google Sheets (Published URL)

on:
  workflow_dispatch:
  schedule:
    - cron: "30 13 * * 1-5"  # 09:30 Toronto ≈ 13:30 UTC

permissions:
  contents: write

jobs:
  pull-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Ensure target folder exists
        run: mkdir -p sheets

      - name: DEBUG: show HTTP status for published CSV
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            "https://docs.google.com/spreadsheets/d/e/2PACX-1vTpvBTBr4zzHKpcLc9V8vOCSFTvRJBaSvYWtOHrQbWTruTz3NYjAEfHnTDIdpCj2tCpYihiBXcjUHYh/pub?gid=GID_SCAN&single=true&output=csv")
          echo "HTTP_STATUS=$STATUS"
          test "$STATUS" = "200"

      - name: Fetch SCAN CSV (published → preserves headers)
        run: |
          curl -fSL \
            "https://docs.google.com/spreadsheets/d/e/2PACX-1vTpvBTBr4zzHKpcLc9V8vOCSFTvRJBaSvYWtOHrQbWTruTz3NYjAEfHnTDIdpCj2tCpYihiBXcjUHYh/pub?gid=GID_SCAN&single=true&output=csv" \
            -o sheets/SCAN.csv

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add sheets/SCAN.csv
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Mirror: SCAN.csv from Google Sheets (published)"
          git push
