name: Mirror SCAN from Google Sheets (Export Endpoint)

on:
  schedule:
    # 13:30 UTC = 09:30 America/Toronto on weekdays
    - cron: "30 13 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: mirror-scan-pull
  cancel-in-progress: false

jobs:
  mirror_scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      SHEET_ID: ${{ secrets.SHEET_ID }}
      GID_SCAN: ${{ secrets.GID_SCAN }}   # set this secret to the SCAN tab's gid

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show UTC/Toronto time (for logs)
        run: |
          echo "UTC:      $(date -u +%FT%TZ)"
          TZ=America/Toronto date "+Toronto: %Y-%m-%d %H:%M:%S %Z (%z)"

      - name: Ensure publisher script is executable
        run: chmod +x scripts/publish_tab.sh

      - name: Export & publish SCAN (no incremental; snapshot)
        run: |
          scripts/publish_tab.sh \
            --sheet-id "${SHEET_ID}" \
            --tab-name "SCAN" \
            --gid "${GID_SCAN}" \
            --branch "main" \
            --chunk-size 600

      - name: Commit & push SCAN artifacts
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add sheets/SCAN.csv live/SCAN/** || true
          git commit -m "Mirror SCAN: export + /live artifacts" || echo "No changes"
          git push

      # Optional: make quick preview files downloadable from the run
      - name: Upload head/schema preview (optional)
        uses: actions/upload-artifact@v4
        with:
          name: SCAN-preview
          path: |
            live/SCAN/head.csv
            live/SCAN/schema.json
          if-no-files-found: ignore
