name: Morning Mirror — Full Workbook + Key CSVs

on:
  schedule:
    # 12:00 UTC = 08:00 America/Toronto on weekdays
    - cron: "0 12 * * 1-5"
  workflow_dispatch:

# Needed to push CSVs & /live artifacts back to the repo
permissions:
  contents: write

# Prevent overlapping runs if one is still going
concurrency:
  group: morning-mirror
  cancel-in-progress: false

jobs:
  mirror:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    env:
      # Sheet + (optional) CSV config (TabName,GID)
      SHEET_ID: ${{ secrets.SHEET_ID }}
      # If you have a config/tabs.csv, leave as-is.
      # If not, see the fallback matrix section below.
      CONFIG_TABS: config/tabs.csv

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show UTC/Toronto time (for logs only)
        run: |
          echo "UTC:      $(date -u +%FT%TZ)"
          TZ=America/Toronto date "+Toronto: %Y-%m-%d %H:%M:%S %Z (%z)"

      - name: Ensure scripts are executable
        run: |
          chmod +x scripts/publish_tab.sh || true
          chmod +x scripts/publish_all_tabs.sh || true

      # ──────────────────────────────────────────────────────────────
      # OPTION A: Drive from config/tabs.csv (recommended)
      #   File format: TabName,GID (with header row)
      #   e.g.
      #     TabName,GID
      #     SCAN,1375435285
      #     H_XIU,111111111
      #     TA_XIU,222222222
      # If scripts/publish_all_tabs.sh exists, use it; else loop locally.
      # ──────────────────────────────────────────────────────────────
      - name: Publish all tabs (from config/tabs.csv)
        if: ${{ env.SHEET_ID != '' && hashFiles(env.CONFIG_TABS) != '' && exists('scripts/publish_all_tabs.sh') }}
        run: |
          ./scripts/publish_all_tabs.sh \
            --sheet-id "${SHEET_ID}" \
            --branch "main" \
            --config "${CONFIG_TABS}"

      - name: Publish all tabs (inline loop; no publish_all_tabs.sh)
        if: ${{ env.SHEET_ID != '' && hashFiles(env.CONFIG_TABS) != '' && !exists('scripts/publish_all_tabs.sh') }}
        run: |
          while IFS=, read -r NAME GID; do
            # skip header
            [[ "$NAME" == "TabName" ]] && continue
            # Incremental 30d only for H_* or TA_*; full replace for others (e.g., SCAN)
            if [[ "$NAME" == H_* || "$NAME" == TA_* ]]; then
              scripts/publish_tab.sh \
                --sheet-id "${SHEET_ID}" \
                --tab-name "${NAME}" \
                --gid "${GID}" \
                --branch "main" \
                --incremental-days 30 \
                --date-col Date \
                --chunk-size 1000
            else
              scripts/publish_tab.sh \
                --sheet-id "${SHEET_ID}" \
                --tab-name "${NAME}" \
                --gid "${GID}" \
                --branch "main" \
                --chunk-size 600
            fi
          done < "${CONFIG_TABS}"

      # ──────────────────────────────────────────────────────────────
      # OPTION B (fallback): No config/tabs.csv?
      #   Use a small matrix of known tabs. Add rows as needed.
      #   Delete this whole job step once A is working.
      # ──────────────────────────────────────────────────────────────
      - name: Fallback — explicitly publish a few tabs (delete once config is used)
        if: ${{ env.SHEET_ID != '' && hashFiles(env.CONFIG_TABS) == '' }}
        run: |
          # SCAN (snapshot; no incremental)
          scripts/publish_tab.sh \
            --sheet-id "${SHEET_ID}" \
            --tab-name "SCAN" \
            --gid "${{ secrets.GID_SCAN }}" \
            --branch "main" \
            --chunk-size 600

          # Example H_/TA_ with incremental tail rewrite
          # (uncomment & set secrets GIDs for your symbols)
          # scripts/publish_tab.sh \
          #   --sheet-id "${SHEET_ID}" \
          #   --tab-name "H_XIU" \
          #   --gid "${{ secrets.GID_H_XIU }}" \
          #   --branch "main" \
          #   --incremental-days 30 \
          #   --date-col Date \
          #   --chunk-size 1000

          # scripts/publish_tab.sh \
          #   --sheet-id "${SHEET_ID}" \
          #   --tab-name "TA_XIU" \
          #   --gid "${{ secrets.GID_TA_XIU }}" \
          #   --branch "main" \
          #   --incremental-days 30 \
          #   --date-col Date \
          #   --chunk-size 1000

      - name: Commit & push artifacts
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add sheets/*.csv live/** || true
          git commit -m "Morning Mirror: publish per-page CSVs + /live artifacts" || echo "No changes"
          git push

      # Optional: upload the latest head/schema for quick inspection in Actions UI
      - name: Upload quick preview artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: live-previews
          path: |
            live/*/head.csv
            live/*/schema.json
          if-no-files-found: ignore
